### ISSUE TITLE
Support of Capsule Tenant CR v1beta1

### ISSUE THREAD

**Issue by bsctl** [clastix/capsule-lens-extension#26]
Introduce the support **Capsule Tenant CRD** `v1beta1` APIs version:

```yaml
apiVersion: capsule.clastix.io/v1beta1
kind: Tenant
metadata:
  name: gas
spec:
  owners:
    -
      kind: User
      name: bob
```
