### ISSUE TITLE
Support of CapsuleConfiguration CR

### ISSUE THREAD

**Issue by bsctl** [clastix/capsule-lens-extension#27]
Introduce support of **CapsuleConfiguration** CRD APIs:

```yaml
apiVersion: capsule.clastix.io/v1alpha1
kind: CapsuleConfiguration
metadata:
  name: default
spec:
  userGroups: ["capsule.clastix.io"]
  forceTenantPrefix: false
  protectedNamespaceRegex: ""
```
